USE analytics;


CREATE TABLE IF NOT EXISTS tbl_eq_data
(
SYMBOL VARCHAR(20),
SERIES VARCHAR(5),
OPEN DECIMAL(10,2),
HIGH DECIMAL(10,2),	
LOW DECIMAL(10,2),
CLOSE DECIMAL(10,2),	
LAST DECIMAL(10,2),	
PREVCLOSE DECIMAL(10,2),	
TOTTRDQTY INT,	
TOTTRDVAL DECIMAL(20,2),	
TIMESTAMP DATE,	
ISIN  VARCHAR(20)
);
